language: python
matrix:
  include:
    - python: 3.5
    - python: 3.6
# command to install dependencies
install:
  - pip install tensorflow
  - pip install coverage
  - pip install pytest-cov
  - pip install codecov
  - pip install -e .[tests]
# command to run tests
script:
  - py.test tests/ --cov=tfdiffeq tests/
after_success:
  - codecov
notifications:
  email:
    on_success: never
    on_failure: always
